--- 
configurations: 
  - 
    description: "DEA Hotspots animation ACT region"
    name: 'acthotspots' #'name of spatial subset'
    sensors: #sensors to use in animation
      -
        AVHRR: ['SRSS']
        MODIS: ['MOD14']
        VIIRS: ['AFMOD', 'EDR'] 
    time_period: 90 #time period prior to now in days
    timezone: 'Australia/Sydney' #timezone for display
    timezone_code: 'AEDT'
    bbox: [-35.0, 148.0, -36.5, 149.5 ] # y_max, x_min, y_min, x_max
    min_confidence: 20 #minimum confidence 0 - 100 percent
    max_features: 500000 #maximum number of features to load from WFS
    frame_freq: '4H' #frame frequency for ffmpeg
    hotspots_markersize: 4 #size to plot hotspots on map
    hotspots_alpha: 0.5 #transparency to plot hotspots on map
    fade_hours: 72 #hours used to fade hotspots
    fade_cmap: '#2B2D2F' #colour for faded hotspots
    hotspots_cmap: 'YlOrRd' #colour ramp for plotting hotspots
    url: "https://gsky.nci.org.au/ows/dea" #WMS for background image
    layer: "landsat8_geomedian" #WMS layer name
  - 
    description: "DEA Hotspots animation Victoria New South Wales"
    name: 'vicnswhotspots' #'name of spatial subset'
    sensors: #sensors to use in animation
      -
        AVHRR: ['SRSS']
        MODIS: ['MOD14']
        VIIRS: ['AFMOD', 'EDR'] 
    time_period: 90 #time period prior to now in days
    timezone: 'Australia/Sydney' #timezone for display
    timezone_code: 'AEDT'
    bbox: [-28.157021, 140.961682, -39.159082, 154.109154 ] # y_max, x_min, y_min, x_max
    min_confidence: 20 #minimum confidence 0 - 100 percent
    max_features: 500000 #maximum number of features to load from WFS
    frame_freq: '4H' #frame frequency for ffmpeg
    hotspots_markersize: 4 #size to plot hotspots on map
    hotspots_alpha: 0.5 #transparency to plot hotspots on map
    fade_hours: 72 #hours used to fade hotspots
    fade_cmap: '#2B2D2F' #colour for faded hotspots
    hotspots_cmap: 'YlOrRd' #colour ramp for plotting hotspots
    url: "https://gsky.nci.org.au/ows/dea" #WMS for background image
    layer: "landsat8_geomedian" #WMS layer name
  - 
    description: "DEA Hotspots animation South Western Australia"
    name: 'swahotspots' #'name of spatial subset'
    sensors: #sensors to use in animation
      -
        AVHRR: ['SRSS']
        MODIS: ['MOD14']
        VIIRS: ['AFMOD', 'EDR']  
    time_period: 90 #time period prior to now in days
    timezone: 'Australia/Perth' #timezone for display
    timezone_code: 'AWST'
    bbox: [-23.688726 , 112.921114, -35.192008, 129.002045] # y_max, x_min, y_min, x_max
    min_confidence: 20 #minimum confidence 0 - 100 percent
    max_features: 500000 #maximum number of features to load from WFS
    frame_freq: '4H' #frame frequency for ffmpeg
    hotspots_markersize: 4 #size to plot hotspots on map
    hotspots_alpha: 0.5 #transparency to plot hotspots on map
    fade_hours: 72 #hours used to fade hotspots
    fade_cmap: '#2B2D2F' #colour for faded hotspots
    hotspots_cmap: 'YlOrRd' #colour ramp for plotting hotspots
    url: "https://gsky.nci.org.au/ows/dea" #WMS for background image
    layer: "landsat8_geomedian" #WMS layer name
  - 
    description: "DEA Hotspots animation North Western Australia"
    name: 'nwahotspots' #'name of spatial subset'
    sensors: #sensors to use in animation
      -
        AVHRR: ['SRSS']
        MODIS: ['MOD14']
        VIIRS: ['AFMOD', 'EDR']  
    time_period: 90 #time period prior to now in days
    timezone: 'Australia/Perth' #timezone for display
    timezone_code: 'AWST'
    bbox: [ -13.688726, 112.921114 , -25.192008, 129.002045 ] # y_max, x_min, y_min, x_max
    min_confidence: 20 #minimum confidence 0 - 100 percent
    max_features: 500000 #maximum number of features to load from WFS
    frame_freq: '4H' #frame frequency for ffmpeg
    hotspots_markersize: 4 #size to plot hotspots on map
    hotspots_alpha: 0.5 #transparency to plot hotspots on map
    fade_hours: 72 #hours used to fade hotspots
    fade_cmap: '#2B2D2F' #colour for faded hotspots
    hotspots_cmap: 'YlOrRd' #colour ramp for plotting hotspots
    url: "https://gsky.nci.org.au/ows/dea" #WMS for background image
    layer: "landsat8_geomedian" #WMS layer name
  - 
    description: "DEA Hotspots animation Queensland"
    name: 'qldhotspots' #'name of spatial subset'
    sensors: #sensors to use in animation
      -
        AVHRR: ['SRSS']
        MODIS: ['MOD14']
        VIIRS: ['AFMOD', 'EDR'] 
    time_period: 90 #time period prior to now in days
    timezone: 'Australia/Brisbane' #timezone for display
    timezone_code: 'AEST'
    bbox: [ -9.142306 , 137.994325 , -29.177893 , 153.552171 ] # y_max, x_min, y_min, x_max
    min_confidence: 20 #minimum confidence 0 - 100 percent
    max_features: 500000 #maximum number of features to load from WFS
    frame_freq: '4H' #frame frequency for ffmpeg
    hotspots_markersize: 4 #size to plot hotspots on map
    hotspots_alpha: 0.5 #transparency to plot hotspots on map
    fade_hours: 72 #hours used to fade hotspots
    fade_cmap: '#2B2D2F' #colour for faded hotspots
    hotspots_cmap: 'YlOrRd' #colour ramp for plotting hotspots
    url: "https://gsky.nci.org.au/ows/dea" #WMS for background image
    layer: "landsat8_geomedian" #WMS layer name
  - 
    description: "DEA Hotspots animation North Territory"
    name: 'nthotspots' #'name of spatial subset'
    sensors: #sensors to use in animation
      -
        AVHRR: ['SRSS']
        MODIS: ['MOD14']
        VIIRS: ['AFMOD', 'EDR']  
    time_period: 90 #time period prior to now in days
    timezone: 'Australia/Darwin' #timezone for display
    timezone_code: 'ACDT'
    bbox: [ -10.905918 , 129.00044 , -25.998614 , 137.999054 ] # y_max, x_min, y_min, x_max
    min_confidence: 20 #minimum confidence 0 - 100 percent
    max_features: 500000 #maximum number of features to load from WFS
    frame_freq: '4H' #frame frequency for ffmpeg
    hotspots_markersize: 4 #size to plot hotspots on map
    hotspots_alpha: 0.5 #transparency to plot hotspots on map
    fade_hours: 72 #hours used to fade hotspots
    fade_cmap: '#2B2D2F' #colour for faded hotspots
    hotspots_cmap: 'YlOrRd' #colour ramp for plotting hotspots
    url: "https://gsky.nci.org.au/ows/dea" #WMS for background image
    layer: "landsat8_geomedian" #WMS layer name
  - 
    description: "DEA Hotspots animation South Australia"
    name: 'sahotspots' #'name of spatial subset'
    sensors: #sensors to use in animation
      -
        AVHRR: ['SRSS']
        MODIS: ['MOD14']
        VIIRS: ['AFMOD', 'EDR']  
    time_period: 90 #time period prior to now in days
    timezone: 'Australia/Adelaide' #timezone for display
    timezone_code: 'ACDT'
    bbox: [ -25.996146 , 129.001337, -38.062117, 141.002956 ] # y_max, x_min, y_min, x_max
    min_confidence: 20 #minimum confidence 0 - 100 percent
    max_features: 500000 #maximum number of features to load from WFS
    frame_freq: '4H' #frame frequency for ffmpeg
    hotspots_markersize: 4 #size to plot hotspots on map
    hotspots_alpha: 0.5 #transparency to plot hotspots on map
    fade_hours: 72 #hours used to fade hotspots
    fade_cmap: '#2B2D2F' #colour for faded hotspots
    hotspots_cmap: 'YlOrRd' #colour ramp for plotting hotspots
    url: "https://gsky.nci.org.au/ows/dea" #WMS for background image
    layer: "landsat8_geomedian" #WMS layer name
  - 
    description: "DEA Hotspots animation Tasmania"
    name: 'tashotspots' #'name of spatial subset'
    sensors: #sensors to use in animation
      -
        AVHRR: ['SRSS']
        MODIS: ['MOD14']
        VIIRS: ['AFMOD', 'EDR'] 
    time_period: 90 #time period prior to now in days
    timezone: 'Australia/Hobart' #timezone for display
    timezone_code: 'AEDT'
    bbox: [ -39.203793 , 143.818923 , -43.740482 , 148.498674 ] # y_max, x_min, y_min, x_max
    min_confidence: 20 #minimum confidence 0 - 100 percent
    max_features: 500000 #maximum number of features to load from WFS
    frame_freq: '4H' #frame frequency for ffmpeg
    hotspots_markersize: 4 #size to plot hotspots on map
    hotspots_alpha: 0.5 #transparency to plot hotspots on map
    fade_hours: 72 #hours used to fade hotspots
    fade_cmap: '#2B2D2F' #colour for faded hotspots
    hotspots_cmap: 'YlOrRd' #colour ramp for plotting hotspots
    url: "https://gsky.nci.org.au/ows/dea" #WMS for background image
    layer: "landsat8_geomedian" #WMS layer name